import {useEffect,useMemo,useState} from 'react'
import {CalendarPlus,Check,ChevronRight,RefreshCw,ShieldCheck,Sparkles,UserPlus,Users} from 'lucide-react'
import {supabase} from './lib/supabase'
import type {Match,Tournament} from './types'

type ClubTeam={id:string;name:string;category:string;active:boolean}
type Division={id:string;tournament_id:string;name:string;pool_count:number;max_teams_per_pool:number;knockout:boolean;third_place:boolean}
type DbTournament={id:string;name:string;event_date:string;venue:string;published:boolean}
type Props={tournament:Tournament;signedIn:boolean;onLogin:()=>void;onRefresh:()=>void;onSelect:(id:string)=>void}

export default function Admin({tournament,signedIn,onLogin,onRefresh,onSelect}:Props){
 const[step,setStep]=useState(1),[clubTeams,setClubTeams]=useState<ClubTeam[]>([]),[selected,setSelected]=useState<string[]>([]),[divisions,setDivisions]=useState<Division[]>([]),[tournaments,setTournaments]=useState<DbTournament[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const[create,setCreate]=useState({name:'',date:'',venue:'Sportpark De Schutskamp'}),[external,setExternal]=useState({name:'',club:'',category:'JO13'}),[referee,setReferee]=useState({name:'',email:'',availability:'Hele dag'})
 async function load(){if(!supabase)return;const[{data:c},{data:d},{data:ts}]=await Promise.all([supabase.from('club_teams').select('*').eq('active',true).order('category').order('name'),supabase.from('divisions').select('*').eq('tournament_id',tournament.id).order('name'),supabase.from('tournaments').select('*').order('event_date',{ascending:false})]);setClubTeams(c??[]);setDivisions(d??[]);setTournaments(ts??[])}
 useEffect(()=>{void load()},[tournament.id])
 async function run(action:()=>Promise<void>,ok:string){setBusy(true);setMessage('');try{await action();setMessage(ok);await load();onRefresh()}catch(e){setMessage(e instanceof Error?e.message:'Actie mislukt')}finally{setBusy(false)}}
 async function createTournament(){await run(async()=>{const{error}=await supabase!.from('tournaments').insert({name:create.name,event_date:create.date,venue:create.venue,published:false});if(error)throw error},'Nieuw toernooi aangemaakt.')}
 async function addSelected(){await run(async()=>{const existing=new Set(tournament.teams.map(x=>x.name));const rows=clubTeams.filter(x=>selected.includes(x.id)&&!existing.has(x.name)).map(x=>({tournament_id:tournament.id,name:x.name,club_name:'sv CHC',pool_name:'Poule A',category:x.category,source:'chc'}));if(!rows.length)throw new Error('De geselecteerde teams staan al in dit toernooi.');const{error}=await supabase!.from('teams').insert(rows);if(error)throw error},`${selected.length} CHC-team(s) toegevoegd.`);setSelected([])}
 async function addExternal(){await run(async()=>{const{error}=await supabase!.from('teams').insert({tournament_id:tournament.id,name:external.name,club_name:external.club,pool_name:'Poule A',category:external.category,source:'external'});if(error)throw error},'Extern team toegevoegd.');setExternal({name:'',club:'',category:'JO13'})}
 async function addDivision(){await run(async()=>{const{error}=await supabase!.from('divisions').insert({tournament_id:tournament.id,name:`Categorie ${divisions.length+1}`,pool_count:2,max_teams_per_pool:6});if(error)throw error},'Categorie toegevoegd.')}
 async function updateDivision(id:string,values:Partial<Division>){await run(async()=>{const{error}=await supabase!.from('divisions').update(values).eq('id',id);if(error)throw error},'Poule-instellingen opgeslagen.')}
 async function distribute(d:Division){const candidates=tournament.teams.filter(x=>x.category===d.name||divisions.length===1);await run(async()=>{for(let i=0;i<candidates.length;i++){const pool=String.fromCharCode(65+(i%d.pool_count));const{error}=await supabase!.from('teams').update({pool_name:`Poule ${pool}`,division_id:d.id}).eq('id',candidates[i].id);if(error)throw error}},'Teams automatisch en gelijkmatig over de poules verdeeld.')}
 async function addReferee(){await run(async()=>{const{error}=await supabase!.from('officials').insert({tournament_id:tournament.id,...referee,role:'Scheidsrechter',active:true});if(error)throw error},'Scheidsrechter toegevoegd.');setReferee({name:'',email:'',availability:'Hele dag'})}
 async function autoAssign(){const refs=tournament.officials??[];const slots=[...new Set(tournament.matches.map(m=>m.kickoff))];await run(async()=>{for(const m of tournament.matches){const slot=slots.indexOf(m.kickoff),field=[...new Set(tournament.matches.filter(x=>x.kickoff===m.kickoff).map(x=>x.field))].indexOf(m.field);const chosen=refs[(slot+field)%refs.length];if(chosen){const{error}=await supabase!.from('matches').update({referee_name:chosen.name}).eq('id',m.id);if(error)throw error}}},'Scheidsrechters conflictvrij over de wedstrijden verdeeld.')}
 async function manual(match:Match,name:string){await run(async()=>{const{error}=await supabase!.from('matches').update({referee_name:name||null}).eq('id',match.id);if(error)throw error},'Scheidsrechter aangepast.')}
 async function generateSchedule(){const fields=(tournament.fields??[]).map(x=>x.name);if(fields.length===0)throw new Error('Voeg eerst velden toe.');const groups=[...new Set(tournament.teams.map(x=>x.pool))];const games:{home:string;away:string;pool:string}[]=[];groups.forEach(pool=>{const teams=tournament.teams.filter(x=>x.pool===pool);for(let i=0;i<teams.length;i++)for(let j=i+1;j<teams.length;j++)games.push({home:teams[i].id,away:teams[j].id,pool})});await run(async()=>{const{error:del}=await supabase!.from('matches').delete().eq('tournament_id',tournament.id);if(del)throw del;const start=9*60,refs=tournament.officials??[];const rows=games.map((g,i)=>{const slot=Math.floor(i/fields.length),minutes=start+slot*25,time=`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;return{tournament_id:tournament.id,pool_name:g.pool,kickoff:time,field_name:fields[i%fields.length],home_team_id:g.home,away_team_id:g.away,status:'scheduled',referee_name:refs.length?refs[(slot+i%fields.length)%refs.length].name:null}});const{error}=await supabase!.from('matches').insert(rows);if(error)throw error},`${games.length} poulewedstrijden gegenereerd.`)}
 const categories=useMemo(()=>[...new Set(clubTeams.map(x=>x.category))],[clubTeams])
 if(!signedIn)return <section className="admin-lock"><ShieldCheck/><h2>Eigenaarstoegang nodig</h2><p>Log in met contributie@svchc.nl om toernooien en deelnemers te beheren.</p><button className="button primary" onClick={onLogin}>Stuur beveiligde inloglink</button></section>
 return <div className="admin-workspace"><div className="admin-steps">{['Toernooien','Teams','Poules','Scheidsrechters'].map((x,i)=><button className={step===i+1?'active':''} onClick={()=>setStep(i+1)} key={x}><span>{i+1}</span>{x}<ChevronRight/></button>)}</div>{message&&<div className="notice good"><Check/><strong>{message}</strong></div>}
 {step===1&&<section className="admin-section"><header><div><span className="context">Meerdere evenementen</span><h2>Toernooien</h2><p>Maak een nieuw toernooi of open een bestaande editie.</p></div><CalendarPlus/></header><div className="admin-grid"><div className="admin-form"><label>Naam<input value={create.name} onChange={e=>setCreate({...create,name:e.target.value})} placeholder="Bijv. CHC Zomertoernooi 2027"/></label><label>Datum<input type="date" value={create.date} onChange={e=>setCreate({...create,date:e.target.value})}/></label><label>Locatie<input value={create.venue} onChange={e=>setCreate({...create,venue:e.target.value})}/></label><button className="button primary" disabled={busy||!create.name||!create.date} onClick={()=>void createTournament()}>Toernooi aanmaken</button></div><div className="admin-list">{tournaments.map(x=><article key={x.id}><div><strong>{x.name}</strong><span>{x.event_date} · {x.venue}</span></div><div className="row-actions"><span className={`pill ${x.published?'success':''}`}>{x.published?'Live':'Concept'}</span><button className="button secondary" onClick={()=>onSelect(x.id)}>{x.id===tournament.id?'Geopend':'Open'}</button></div></article>)}</div></div></section>}
 {step===2&&<section className="admin-section"><header><div><span className="context">Deelnemers</span><h2>CHC-teams selecteren</h2><p>Selecteer meerdere clubteams en voeg externe deelnemers apart toe.</p></div><Users/></header><div className="category-filter">{categories.map(c=><span key={c}>{c}</span>)}</div><div className="club-selector">{clubTeams.map(x=><label key={x.id} className={selected.includes(x.id)?'selected':''}><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(e.target.checked?[...selected,x.id]:selected.filter(id=>id!==x.id))}/><span><strong>{x.name}</strong><small>{x.category}</small></span></label>)}</div><button className="button primary" disabled={!selected.length||busy} onClick={()=>void addSelected()}>{selected.length||0} geselecteerde teams toevoegen</button><div className="subsection"><h3>Extern team toevoegen</h3><div className="inline-admin"><input placeholder="Teamnaam" value={external.name} onChange={e=>setExternal({...external,name:e.target.value})}/><input placeholder="Clubnaam" value={external.club} onChange={e=>setExternal({...external,club:e.target.value})}/><input placeholder="Categorie" value={external.category} onChange={e=>setExternal({...external,category:e.target.value})}/><button className="button secondary" disabled={!external.name||!external.club} onClick={()=>void addExternal()}><UserPlus size={17}/> Toevoegen</button></div></div></section>}
 {step===3&&<section className="admin-section"><header><div><span className="context">Toernooi-opzet</span><h2>Categorieën & poules</h2><p>Bepaal de poulegrootte, verdeel teams en genereer het wedstrijdschema.</p></div><div className="header-actions"><button className="button secondary" onClick={()=>void addDivision()}>Categorie toevoegen</button><button className="button primary" onClick={()=>void generateSchedule()}><CalendarPlus size={17}/> Programma genereren</button></div></header>{divisions.map(d=><article className="division-editor" key={d.id}><input value={d.name} onChange={e=>setDivisions(divisions.map(x=>x.id===d.id?{...x,name:e.target.value}:x))} onBlur={()=>void updateDivision(d.id,{name:d.name})}/><label>Aantal poules<select value={d.pool_count} onChange={e=>void updateDivision(d.id,{pool_count:Number(e.target.value)})}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><label>Teams per poule<select value={d.max_teams_per_pool} onChange={e=>void updateDivision(d.id,{max_teams_per_pool:Number(e.target.value)})}>{[3,4,5,6,7,8,10,12].map(n=><option key={n}>{n}</option>)}</select></label><label className="checkline"><input type="checkbox" checked={d.knockout} onChange={e=>void updateDivision(d.id,{knockout:e.target.checked})}/> Finaleronde</label><button className="button primary" onClick={()=>void distribute(d)}><Sparkles size={17}/> Automatisch verdelen</button></article>)}</section>}
 {step===4&&<section className="admin-section"><header><div><span className="context">Wedstrijdleiding</span><h2>Scheidsrechters</h2><p>Voeg officials toe en kies automatisch of per wedstrijd.</p></div><button className="button primary" disabled={!tournament.officials?.length||busy} onClick={()=>void autoAssign()}><Sparkles size={17}/> Automatisch indelen</button></header><div className="inline-admin"><input placeholder="Naam" value={referee.name} onChange={e=>setReferee({...referee,name:e.target.value})}/><input type="email" placeholder="E-mailadres" value={referee.email} onChange={e=>setReferee({...referee,email:e.target.value})}/><input placeholder="Beschikbaarheid" value={referee.availability} onChange={e=>setReferee({...referee,availability:e.target.value})}/><button className="button secondary" disabled={!referee.name} onClick={()=>void addReferee()}>Toevoegen</button></div><div className="assignment-table"><div className="assignment-head"><span>Tijd/veld</span><span>Wedstrijd</span><span>Scheidsrechter</span></div>{tournament.matches.map(m=><div className="assignment-row" key={m.id}><span><strong>{m.kickoff}</strong><small>{m.field}</small></span><span>{tournament.teams.find(x=>x.id===m.homeTeamId)?.name} – {tournament.teams.find(x=>x.id===m.awayTeamId)?.name}</span><select value={m.referee??''} onChange={e=>void manual(m,e.target.value)}><option value="">Niet toegewezen</option>{tournament.officials?.map(o=><option key={o.id}>{o.name}</option>)}</select></div>)}</div></section>}
 {busy&&<div className="admin-busy"><RefreshCw className="spin"/> Opslaan…</div>}</div>
}
