import {useEffect,useMemo,useState} from 'react'
import {CalendarDays,ChevronRight,ClipboardList,LayoutDashboard,Menu,Radio,RefreshCw,ShieldCheck,Table2,Trophy,Users,X} from 'lucide-react'
import {calculateStandings} from './standings'
import type {Match,Tournament} from './types'
import {hasSupabase} from './lib/supabase'
import {loadTournament,subscribeToTournament,updateScore} from './lib/tournament-api'
import {supabase} from './lib/supabase'

type View='overview'|'matches'|'standings'|'teams'|'manage'
const nav=[{id:'overview',label:'Overzicht',icon:LayoutDashboard},{id:'matches',label:'Programma',icon:CalendarDays},{id:'standings',label:'Standen',icon:Table2},{id:'teams',label:'Teams',icon:Users},{id:'manage',label:'Beheer',icon:ShieldCheck}] as const

function Mark(){return <div className="mark" aria-label="SV CHC"><span>CHC</span><small>TOURNAMENT</small></div>}
function teamName(tournament:Tournament,id:string){return tournament.teams.find(t=>t.id===id)?.name??'Onbekend team'}
function Status({status}:{status:Match['status']}){const text={scheduled:'Gepland',live:'Live',finished:'Afgelopen'}[status];return <span className={`status ${status}`}>{status==='live'&&<i/>}{text}</span>}

function MatchRow({match,tournament,onSelect}:{match:Match;tournament:Tournament;onSelect?:(match:Match)=>void}){
 return <button className="match-row" onClick={()=>onSelect?.(match)} disabled={!onSelect}>
  <div className="match-meta"><strong>{match.kickoff}</strong><span>{match.field}</span></div>
  <div className="fixture"><span>{teamName(tournament,match.homeTeamId)}</span><span>{teamName(tournament,match.awayTeamId)}</span></div>
  <div className="score"><strong>{match.homeScore??'–'}</strong><strong>{match.awayScore??'–'}</strong></div>
  <Status status={match.status}/>{onSelect&&<ChevronRight size={18} aria-hidden="true"/>}
 </button>
}

function Overview({tournament,setView}:{tournament:Tournament;setView:(v:View)=>void}){
 const live=tournament.matches.filter(m=>m.status==='live'),next=tournament.matches.filter(m=>m.status==='scheduled').slice(0,3)
 return <><header className="page-heading"><div><p className="context">Wedstrijddag</p><h1>{tournament.name}</h1><p>{tournament.date} · {tournament.venue}</p></div><button className="button secondary" onClick={()=>setView('matches')}>Bekijk programma</button></header>
 <section className="signal"><div><Radio/><div><span>Toernooi live</span><strong>{live.length?`${live.length} wedstrijd${live.length===1?'':'en'} bezig`:'Geen wedstrijd bezig'}</strong></div></div><div><span>Teams</span><strong>{tournament.teams.length}</strong></div><div><span>Wedstrijden</span><strong>{tournament.matches.length}</strong></div><div><span>Afgerond</span><strong>{tournament.matches.filter(m=>m.status==='finished').length}</strong></div></section>
 <div className="columns"><section><div className="section-title"><div><h2>Nu op het veld</h2><p>Live uitslagen worden automatisch bijgewerkt.</p></div></div><div className="match-list">{live.length?live.map(m=><MatchRow key={m.id} match={m} tournament={tournament}/>):<div className="empty">Zodra een wedstrijd start, verschijnt die hier.</div>}</div></section>
 <section><div className="section-title"><div><h2>Hierna</h2><p>De eerstvolgende wedstrijden.</p></div><button className="text-button" onClick={()=>setView('matches')}>Alles bekijken</button></div><div className="match-list">{next.map(m=><MatchRow key={m.id} match={m} tournament={tournament}/>)}</div></section></div></>
}

function Matches({tournament,onSelect}:{tournament:Tournament;onSelect?:(m:Match)=>void}){const groups=tournament.matches.reduce<Record<string,Match[]>>((all,match)=>{(all[match.kickoff]??=[]).push(match);return all},{});return <><header className="page-heading"><div><p className="context">Wedstrijdschema</p><h1>Programma</h1><p>{tournament.matches.length} wedstrijden op {new Set(tournament.matches.map(m=>m.field)).size} velden</p></div></header>{Object.entries(groups).map(([time,matches])=><section className="schedule-group" key={time}><div className="time-marker"><span>{time}</span></div><div className="match-list">{matches.map(m=><MatchRow key={m.id} match={m} tournament={tournament} onSelect={onSelect}/>)}</div></section>)}</>}

function Standings({tournament}:{tournament:Tournament}){const pools=[...new Set(tournament.teams.map(t=>t.pool))];return <><header className="page-heading"><div><p className="context">Automatisch berekend</p><h1>Standen</h1><p>Winst 3 punten, gelijkspel 1 punt.</p></div></header><div className="standings-grid">{pools.map(pool=><section className="table-section" key={pool}><h2>{pool}</h2><div className="table-scroll"><table><thead><tr><th>#</th><th>Team</th><th>G</th><th>DV</th><th>DT</th><th>+/-</th><th>PT</th></tr></thead><tbody>{calculateStandings(tournament.teams,tournament.matches,pool).map((r,i)=><tr key={r.team.id}><td><span className="rank">{i+1}</span></td><th>{r.team.name}</th><td>{r.played}</td><td>{r.goalsFor}</td><td>{r.goalsAgainst}</td><td>{r.goalsFor-r.goalsAgainst}</td><td><strong>{r.points}</strong></td></tr>)}</tbody></table></div></section>)}</div></>}

function Teams({tournament}:{tournament:Tournament}){const pools=[...new Set(tournament.teams.map(t=>t.pool))];return <><header className="page-heading"><div><p className="context">Deelnemers</p><h1>Teams</h1><p>{tournament.teams.length} teams verdeeld over {pools.length} poules.</p></div></header><div className="team-groups">{pools.map(pool=><section key={pool}><h2>{pool}</h2>{tournament.teams.filter(t=>t.pool===pool).map(t=><div className="team-row" key={t.id}><span className="team-badge">{t.name.slice(0,2).toUpperCase()}</span><div><strong>{t.name}</strong><span>{t.club}</span></div></div>)}</section>)}</div></>}

function ScoreEditor({match,tournament,onClose,onSaved}:{match:Match;tournament:Tournament;onClose:()=>void;onSaved:()=>void}){const [home,setHome]=useState(match.homeScore??0),[away,setAway]=useState(match.awayScore??0),[saving,setSaving]=useState(false),[error,setError]=useState('');async function save(){setSaving(true);setError('');try{await updateScore(match.id,home,away,'finished');onSaved();onClose()}catch(e){setError(e instanceof Error?e.message:'Opslaan mislukt')}finally{setSaving(false)}}return <div className="dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="score-title"><button className="icon-button close" onClick={onClose} aria-label="Sluiten"><X/></button><p className="context">{match.kickoff} · {match.field}</p><h2 id="score-title">Uitslag invoeren</h2><div className="score-editor"><label><span>{teamName(tournament,match.homeTeamId)}</span><input type="number" min="0" inputMode="numeric" value={home} onChange={e=>setHome(Math.max(0,Number(e.target.value)))}/></label><b>–</b><label><span>{teamName(tournament,match.awayTeamId)}</span><input type="number" min="0" inputMode="numeric" value={away} onChange={e=>setAway(Math.max(0,Number(e.target.value)))}/></label></div>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" onClick={save} disabled={saving||!hasSupabase}>{saving?'Opslaan…':hasSupabase?'Uitslag bevestigen':'Supabase-configuratie nodig'}</button></section></div>}

function Manage({tournament,onSelect,signedIn}:{tournament:Tournament;onSelect:(m:Match)=>void;signedIn:boolean}){const[email,setEmail]=useState(''),[message,setMessage]=useState('');async function login(){if(!supabase||!email)return;const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});setMessage(error?error.message:'Controleer je e-mail voor de beveiligde inloglink.')}return <><header className="page-heading"><div><p className="context">Wedstrijdleiding</p><h1>Beheer</h1><p>Open een wedstrijd om de eindstand veilig te bevestigen.</p></div><span className={`connection ${hasSupabase?'connected':''}`}>{hasSupabase?'Realtime verbonden':'Demomodus'}</span></header>{!hasSupabase?<div className="notice"><ShieldCheck/><div><strong>Supabase is nog niet gekoppeld</strong><p>Publieke voorbeelddata werkt, maar scorewijzigingen worden pas opgeslagen nadat de twee Vercel-omgevingsvariabelen zijn toegevoegd.</p></div></div>:!signedIn?<section className="auth-panel"><ShieldCheck/><div><h2>Inloggen voor score-invoer</h2><p>Je ontvangt een eenmalige, beveiligde inloglink. Alleen toegewezen wedstrijdleiding en scorekeepers mogen uitslagen aanpassen.</p><div className="auth-form"><label><span>E-mailadres</span><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="naam@svchc.nl"/></label><button className="button primary" onClick={()=>void login()}>Stuur inloglink</button></div>{message&&<p className="form-message" role="status">{message}</p>}</div></section>:<section><div className="section-title"><div><h2>Score-invoer</h2><p>Alle geplande en actieve wedstrijden.</p></div><button className="text-button" onClick={()=>void supabase?.auth.signOut()}>Uitloggen</button></div><div className="match-list">{tournament.matches.map(m=><MatchRow key={m.id} match={m} tournament={tournament} onSelect={onSelect}/>)}</div></section>}</>}

export default function App(){const [view,setView]=useState<View>('overview'),[menu,setMenu]=useState(false),[tournament,setTournament]=useState<Tournament|null>(null),[error,setError]=useState(''),[editing,setEditing]=useState<Match|null>(null),[signedIn,setSignedIn]=useState(false)
 const refresh=async()=>{try{setTournament(await loadTournament());setError('')}catch{setError('Live gegevens konden niet worden geladen. Probeer het opnieuw.')}}
 useEffect(()=>{void refresh();if(!supabase)return;void supabase.auth.getSession().then(({data})=>setSignedIn(Boolean(data.session)));const{data}=supabase.auth.onAuthStateChange((_event,session)=>setSignedIn(Boolean(session)));return()=>data.subscription.unsubscribe()},[]);useEffect(()=>tournament?subscribeToTournament(tournament.id,()=>void refresh()):undefined,[tournament?.id]);const active=useMemo(()=>nav.find(n=>n.id===view)!,[view]);
 if(!tournament)return <div className="loading"><RefreshCw className="spin"/><span>Toernooi laden…</span></div>
 return <div className="app"><aside className={menu?'open':''}><div className="brand"><Mark/><button className="icon-button mobile-only" onClick={()=>setMenu(false)} aria-label="Menu sluiten"><X/></button></div><nav aria-label="Hoofdnavigatie">{nav.map(item=><button key={item.id} className={view===item.id?'active':''} onClick={()=>{setView(item.id);setMenu(false)}}><item.icon/><span>{item.label}</span></button>)}</nav><div className="club-note"><Trophy/><div><strong>sv CHC</strong><span>'s-Hertogenbosch</span></div></div></aside>{menu&&<button className="scrim" onClick={()=>setMenu(false)} aria-label="Menu sluiten"/>}<main><div className="mobile-header"><button className="icon-button" onClick={()=>setMenu(true)} aria-label="Menu openen"><Menu/></button><Mark/><span className="live-dot" title="Live"/></div>{error&&<div className="error-banner" role="alert">{error}<button onClick={()=>void refresh()}>Opnieuw</button></div>}<div className="content">{view==='overview'&&<Overview tournament={tournament} setView={setView}/>} {view==='matches'&&<Matches tournament={tournament}/>} {view==='standings'&&<Standings tournament={tournament}/>} {view==='teams'&&<Teams tournament={tournament}/>} {view==='manage'&&<Manage tournament={tournament} onSelect={setEditing} signedIn={signedIn}/>}</div><nav className="bottom-nav" aria-label="Mobiele navigatie">{nav.slice(0,4).map(item=><button key={item.id} className={view===item.id?'active':''} onClick={()=>setView(item.id)}><item.icon/><span>{item.label}</span></button>)}</nav></main>{editing&&<ScoreEditor match={editing} tournament={tournament} onClose={()=>setEditing(null)} onSaved={()=>void refresh()}/>}<span className="sr-only" aria-live="polite">{active.label}</span></div>}
