import type {Tournament} from './types'

export const demoTournament:Tournament={id:'00000000-0000-0000-0000-000000000001',name:'CHC Jeugdtoernooi 2026',date:'13 juni 2026',venue:'Sportpark De Schutskamp',published:true,teams:[
 {id:'t1',name:'CHC/Loomer JO13-1',club:'sv CHC',pool:'Poule A'},{id:'t2',name:'OJC Rosmalen JO13-1',club:'OJC Rosmalen',pool:'Poule A'},{id:'t3',name:'FC Engelen JO13-1',club:'FC Engelen',pool:'Poule A'},{id:'t4',name:'Wilhelmina JO13-1',club:'Wilhelmina',pool:'Poule A'},{id:'t5',name:'CHC/Loomer MO13-1',club:'sv CHC',pool:'Poule B'},{id:'t6',name:'RKVV Nieuwkuijk MO13-1',club:'Nieuwkuijk',pool:'Poule B'}
],fields:[{id:'f1',name:'Veld 1',surface:'Natuurgras',status:'open'},{id:'f2',name:'Veld 2',surface:'Kunstgras',status:'open'},{id:'f3',name:'Veld 3',surface:'Kunstgras',status:'open'}],officials:[{id:'o1',name:'Sam de Wit',role:'Scheidsrechter',availability:'09:00–14:00',matches:3},{id:'o2',name:'Noah Jansen',role:'Scheidsrechter',availability:'09:00–13:00',matches:2},{id:'o3',name:'Lina Peters',role:'Scheidsrechter',availability:'Hele dag',matches:3}],volunteers:[{id:'v1',name:'Sanne Vermeer',task:'Wedstrijdsecretariaat',shift:'08:30–13:00',status:'confirmed'},{id:'v2',name:'Mike de Jong',task:'Teamontvangst',shift:'08:30–11:30',status:'confirmed'},{id:'v3',name:'Nog invullen',task:'Kantine',shift:'12:00–16:00',status:'needed'}],sponsors:[{id:'s1',name:'Jumbo Boschveld',contact:'Lokale ondernemer',stage:'Gesprek',score:82,value:350,package:'Reclamebord',nextAction:'Belafspraak inplannen'},{id:'s2',name:'Van Mossel',contact:'Marketing',stage:'Voorstel',score:76,value:1250,package:'Toernooipartner',nextAction:'Voorstel opvolgen'},{id:'s3',name:'Lokale fysiopraktijk',contact:'Eigenaar',stage:'Benaderen',score:68,value:500,package:'Team / materiaal',nextAction:'Persoonlijke mail sturen'}],matches:[
 {id:'m1',kickoff:'09:30',field:'Veld 1',homeTeamId:'t1',awayTeamId:'t2',homeScore:2,awayScore:1,status:'finished',pool:'Poule A',referee:'Sam de Wit',stage:'Poulefase',duration:20},
 {id:'m2',kickoff:'09:30',field:'Veld 2',homeTeamId:'t3',awayTeamId:'t4',homeScore:0,awayScore:0,status:'finished',pool:'Poule A',referee:'Noah Jansen'},
 {id:'m3',kickoff:'10:00',field:'Veld 1',homeTeamId:'t5',awayTeamId:'t6',homeScore:1,awayScore:0,status:'live',pool:'Poule B',referee:'Lina Peters'},
 {id:'m4',kickoff:'10:00',field:'Veld 2',homeTeamId:'t1',awayTeamId:'t3',homeScore:null,awayScore:null,status:'scheduled',pool:'Poule A',referee:'Sam de Wit'},
 {id:'m5',kickoff:'10:30',field:'Veld 1',homeTeamId:'t2',awayTeamId:'t4',homeScore:null,awayScore:null,status:'scheduled',pool:'Poule A',referee:'Noah Jansen'}
]}
